### ISSUE TITLE
Form Inputs with inset icons

### ISSUE THREAD

**Issue by L3V147H4N** [connors/photon#14]
This is purely a aesthetic feature but it's pretty neat nonetheless and it also helps to save some space and create a better feeling to the UX

[Bootstrap Forms](http://getbootstrap.com/css/#forms) 

Another example

![osx search](https://cloud.githubusercontent.com/assets/5846479/10472165/f49afc22-71f3-11e5-87fd-f0d13d2eb89c.png)

**Comment by brunowego** [comment]
Cool :+1:

**Comment by developit** [comment]
Here's my suggestion:
http://jsfiddle.net/developit/aqu10kd9/
![preview](https://i.gyazo.com/ff70bbf75b7f95d19e8546eb18364068.gif)

### Markup

```html
<label class="toolbar-input">
    <span class="icon icon-search"></span>
    <input type="search" class="form-control" placeholder="Search...">
</label>
```

### CSS

```css
/* Here's my suggestion for the CSS */
.toolbar-input {
    position: relative;
    overflow: visible;
    margin: 0;
    padding: 0;
    .icon {
        position: absolute;
        left: 10px;
        top: 4px;
        z-index: 1;
        opacity: 0.5;  /* ~matches placeholder */
    }
    .form-control {
        padding: 3px 4px 1px 24px;
        border-radius: 12px;
        box-shadow: inset 0 1px 2px rgba(0,0,0,0.4),
                    0 0 0 7px rgba(109,179,253,0);
        
        &:focus {
            /* something like this was already in place: */
            box-shadow: inset 0 1px 2px rgba(0,0,0,0.4),
                        0 0 0 1px rgba(109,179,253,0.8);
            transition: box-shadow 250ms ease-out;
        }
    }
}
```
