### ISSUE TITLE
toolbar-header is not draggable by default

### ISSUE THREAD

**Issue by parro-it** [connors/photon#22]
When using a frameless-window, only 
toolbar-footer is draggable, I think we have to add

```css
.toolbar-header {
   -webkit-app-region: drag;
}
```

By the way, photon is really awesome!
