### ISSUE TITLE
More accurate input focus ring

### ISSUE THREAD

**Issue by developit** [connors/photon#54]
I'd like to suggest a more accurate (at least in terms of OS X) input focus outline/border including the nice little animation Apple added in Yosemite.

### Preview:
![preview](https://i.gyazo.com/dc25acb5ddfdc19ab1c99a6e1799e83d.gif)

### JSFiddle Demo:
http://jsfiddle.net/developit/2xpnn03s/

### SCSS:

```css
.form-control {
    box-shadow: 0 0 0 7px rgba(109,179,253,0);

    &:focus {
        box-shadow: 0 0 0 1px rgba(109,179,253,0.8);
        transition: box-shadow 250ms ease-out;
        cursor: text;
    }
}
```

... thoughts?
