### ISSUE TITLE
CSS: Issues with one-third-width pane

### ISSUE THREAD

**Issue by RaoOfPhysics** [connors/photon#60]
In `photon.css`, the following doesn't work (takes up 50% of the container instead of 33.3%):

```CSS
.pane-one-third {
  width: 33.3%;
}
```

Unless `flex:none;` is added to it:

```CSS
.pane-one-third {
  width: 33.3%;
  flex: none;
}
```
