### ISSUE TITLE
Too many global styles!

### ISSUE THREAD

**Issue by Huxpro** [connors/photon#98]
I dont know is it a bug or feature request. But I have to said there is tooooo many global styles applied to basic html elements which really makes UI broken unexpectedly.

**Comment by thiakil** [comment]
Can you give an example of how/where you're using tables that you don't want to have the default styles?

**Comment by xiaokaike** [comment]
Too many global styles!
i don't want  the actrve style in my table
``` css
tr:active,
.table-striped tr:active:nth-child(even) {
  color: #fff;
  background-color: #116cd6;
}

thead tr:active {
  color: #333;
  background-color: #f5f5f4;
}
```
